### ISSUE TITLE
User sign in / sign out / sign up

### ISSUE THREAD

**Issue by tapaswenipathak** [tapaswenipathak/CFP#33]
@sujaykumarreddy 

- User privileges assigned as per the actions
- Multi user
  - Organiser
  - Speaker
  - Admin
  - Stakeholder
- As less as urls as can be
- model design - @tapaswenipathak posts

**Comment by sujaykumarreddy** [comment]
Instead of assigning privileges we can build models around django's user model,and by defining defining proper queries to the database and rendering the forms we can limit how user can interact.

We can define separate tables for profile, events, organizers, proposals and all these are related to each other, and values can be assigned according to user actions.

With extensive use of signals and proper models we can get all the functionality we need.

@tapaswenipathak please let me know what you think.

**Comment by tapaswenipathak** [comment]
On Thu, May 23, 2019 at 1:20 AM sujay Reddy <notifications@github.com> wrote:
>
> Instead of assigning privileges we can write model around django's user model,and by defining defining proper queries to the database and rendering the forms we can limit how user can interact.
>
> We can define separate tables for profile, events, organizers, proposals, and values can be assigned according to the user actions.
>
> With extensive use of signals and proper models we can get all the functionality we need.
>
> @tapaswenipathak please let me know what you think.

Yeah, sounds good, I will cut a design.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or mute the thread.



-- 
Tapasweni

**Comment by tapaswenipathak** [comment]
>  Instead of assigning privileges we can write model around django's user model,and by defining defining proper queries to the database and rendering the forms we can limit how user can interact.

oh no, privileges should be restricted, give me till morning time, I will cut model design as discussed, don't stall the work, continue on writing model as we discussed.

**Comment by tapaswenipathak** [comment]
Multi user separate auth

![E6EDF73E-9AA1-4E40-B6E8-0534585F8F8C](https://user-images.githubusercontent.com/4143778/58227078-0580fc00-7d47-11e9-9c00-c99656ae6c36.png)

**Comment by tapaswenipathak** [comment]
User privileges based on user action

![64FD9046-0D04-4884-8A89-B1DA5DE26F00](https://user-images.githubusercontent.com/4143778/58227427-6d841200-7d48-11e9-96f9-b22c032ac7db.png)

![3BE493CF-A36D-4B2D-B3A3-3FD1550FD76C](https://user-images.githubusercontent.com/4143778/58227659-5e519400-7d49-11e9-98b4-5faf06bfe94b.png)

**Comment by tapaswenipathak** [comment]
Sorry for the bad hand writing, rushed. We can have a call if you feel like https://calendly.com/tapaswenipathak.

**Comment by tapaswenipathak** [comment]
Sorry for the bad hand writing, made in rush. We can have a call if you feel like https://calendly.com/tapaswenipathak.

**Comment by tapaswenipathak** [comment]
Sorry for the bad hand writing. We can have a call if you feel like.
