### ISSUE TITLE
Forms' fields

### ISSUE THREAD

**Issue by tapaswenipathak** [tapaswenipathak/CFP#45]
User Sign up
------------

- username
- password
- email id
- name
- organisation

User sign in
-------------

- username/email id
- password

Presentation
-------------

- Author Name
- Abstract
- Video presentation
- Outline
- Pitch
- Talk time

Conference
-----------

- Venue
- Title
- Start Date
- End Date
- Information
- Topic Tags

**Comment by sujay0399** [comment]
Completed
