### ISSUE TITLE
Completion of tickets

### ISSUE THREAD

**Issue by tapaswenipathak** [tapaswenipathak/CFP#47]
Within a day see you finish all tickets assigned; I am all only on https://github.com/tapaswenipathak/JHEPC-19.

**Comment by sujay0399** [comment]
ack

**Comment by sujaykumarreddy** [comment]
@tapaswenipathak I completed most of the tickets.I will fix some bugs and make a pr tomorrow.

**Comment by tapaswenipathak** [comment]
On Thu, Jun 6, 2019 at 12:20 PM sujay Reddy <notifications@github.com> wrote:
>
> @tapaswenipathak I completed most of the tickets. I will fix few more and make a pr.

Great! Let's chat in Slack and see where the work is.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or mute the thread.



-- 
Tapasweni
