### ISSUE TITLE
Testing CFP app

### ISSUE THREAD

**Issue by tapaswenipathak** [tapaswenipathak/CFP#51]
@EmAchieng You would be testing CFP on these things

- Design testing
  - Add screenshots on this ticket
- Different screen devices
  - Add screenshots on this ticket
- Functionalities, you can find tickets in https://github.com/tapaswenipathak/CFP/issues
  - Add screenshots on this ticket
- Write docs
  - PR in CFP
- Write test code
  - PR in CFP
- Automate things like login, scraping, bulk submit form, bulk querying. 
  - Scripts in CFP

For any questions speak w/ @sujaykumarreddy.

**Comment by EmAchieng** [comment]
Hello,

Is the project still open for me to join.

Thanks so much.

Emily

**Comment by tapaswenipathak** [comment]
On Thu, Dec 12, 2019 at 11:51 AM Emily Achieng <notifications@github.com> wrote:
>
> Hello,
>
> Is the project still open for me to join.

Sure, let me know if you have any questions.
